
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd147258
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    suffix: .html

